import { useMemo } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, ClipboardCheck, Lock, Minus, ScanSearch, ShieldCheck, Timer } from "lucide-react";
import PageShell from "@/components/layout/PageShell";
import JsonLd from "@/components/JsonLd";
import ProPromo from "@/components/ProPromo";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { HeroHouse } from "@/components/illustrations";
import { SectionHeading, SourceBadge } from "@/components/ui-kit";
import { ToolIcon } from "@/components/ToolIcon";
import { firstSentence, generatePlan } from "@/lib/plan";
import { TOOLS } from "@/lib/site";
import { PRO_PRICE_LABEL } from "@/lib/api";
import { SOURCES, SOURCES_REVIEWED } from "@/lib/sources";

const STEPS = [
  { icon: ScanSearch, title: "Tell us what you've seen", body: "Seven quick questions about signs, rooms, your household and what you've tried. Nothing to upload and no account needed." },
  { icon: ClipboardCheck, title: "Get a plan you can act on", body: "A prioritised checklist for today, this week and ongoing, with a printable PDF and calendar reminders." },
  { icon: Timer, title: "Work through it, step by step", body: "Tick steps off as you go. Progress is saved on your device so you can come back any time." },
];

const FAQ = [
  { q: "Is the planner really free?", a: "Yes. The plan, the four tools, the PDF and the calendar reminders are free, with no signup or email required. The optional Pro Masterplan is a separate one-time purchase." },
  { q: "Can it tell me whether I have mice, which species they are or how many?", a: "No, and no online tool honestly can. Droppings, noises and odors can't establish an animal, a species or a number. The planner organises safe, sourced next steps around what you actually observed." },
  { q: "Is the plan generated by AI?", a: "No. It's built from fixed rules written from CDC and UC IPM guidance. The same answers always produce the same plan, and every recommendation is tagged with its source." },
  { q: "Where does my information go?", a: "Your answers stay in your browser. They're not sent to us. If you choose email check-ins, your name and email go to our email provider. If you buy Pro, Stripe handles payment and we receive confirmation of the purchase, not your card details." },
  { q: "What does the Pro Masterplan add, and how does paying work?", a: `Pro adds a dated 30-day schedule, full room protocols, a trap layout helper, an evidence log with a weekly chart, a sealing materials guide, a supply checklist, a pro-call kit and a workbook PDF. It's ${PRO_PRICE_LABEL} once, paid through Stripe. After payment you're returned here, we confirm the purchase with Stripe and unlock your workspace. An access link is also emailed so you can restore it on any device.` },
  { q: "Will following the plan solve my mouse problem?", a: "We can't promise that. The plan follows the approaches the CDC and UC IPM describe (food control, trapping, safe cleanup and sealing gaps), but every home is different. If signs continue, get professional help." },
];

const COMPARE: [string, string | boolean, string | boolean][] = [
  ["Personalised action plan: today, this week, ongoing", true, true],
  ["Safe cleanup, trap placement and entry-gap guides", true, true],
  ["Printable PDF of your plan", true, true],
  ["Calendar reminders for trap checks", "14 days", "Full 30-day schedule"],
  ["Dated 30-day schedule tailored to your answers", false, true],
  ["Room-by-room protocols", "Short prompts", "Full protocols"],
  ["Trap layout helper (UC IPM spacing)", false, true],
  ["Evidence log with weekly chart and CSV export", false, true],
  ["Supply checklist and sealing materials guide", "Basics", "Detailed"],
  ["When-to-call-a-pro kit and seasonal calendar", false, true],
  ["Pro PDF workbook with log sheets", false, true],
];

const Cell = ({ v }: { v: string | boolean }) =>
  v === true ? <Check className="mx-auto h-5 w-5 text-success" aria-label="Included" /> : v === false ? <Minus className="mx-auto h-5 w-5 text-muted-foreground/50" aria-label="Not included" /> : <span className="text-sm font-medium">{v}</span>;

export default function Index() {
  const sample = useMemo(() => generatePlan({ evidence: ["droppings", "gnaw_marks"], location: ["kitchen"], home_type: "detached", household: ["kids", "pets_cat"], previous: ["glue_traps"], food_storage: "mixed", duration: "weeks" }), []);
  const faqLd = useMemo(() => ({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: FAQ.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) }), []);

  return (
    <PageShell>
      <JsonLd id="faq" data={faqLd} />

      <header className="bg-hero hero-pattern text-primary-foreground">
        <div className="container-page grid items-center gap-10 py-14 md:py-20 lg:grid-cols-[1.15fr_1fr]">
          <div>
            <p className="eyebrow mb-4 !text-accent">Mouse Control Planner · Free</p>
            <h1 className="text-4xl font-extrabold leading-[1.08] sm:text-5xl lg:text-[3.4rem]">A clear, source-backed plan for your mouse problem</h1>
            <p className="mt-5 max-w-xl text-lg leading-relaxed text-primary-foreground/85">Answer seven quick questions. Get what to do <strong className="text-primary-foreground">today, this week and ongoing</strong>, grounded in CDC and UC IPM guidance. No signup, no email, no guesswork.</p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button asChild variant="hero" size="xl" className="w-full sm:w-auto"><Link to="/quiz">Build my free plan<ArrowRight className="h-5 w-5" aria-hidden="true" /></Link></Button>
              <Button asChild variant="hero-outline" size="xl" className="w-full sm:w-auto"><a href="#how-it-works">See how it works</a></Button>
            </div>
            <ul className="mt-8 grid max-w-xl grid-cols-2 gap-x-6 gap-y-3 text-sm text-primary-foreground/85">
              <li className="flex items-center gap-2"><Timer className="h-4 w-4 text-accent" aria-hidden="true" />About two minutes</li>
              <li className="flex items-center gap-2"><Lock className="h-4 w-4 text-accent" aria-hidden="true" />Answers stay on your device</li>
              <li className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-accent" aria-hidden="true" />Every step cites its source</li>
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-accent" aria-hidden="true" />Printable PDF included</li>
            </ul>
          </div>
          <div className="mx-auto w-full max-w-md lg:max-w-none"><HeroHouse className="h-auto w-full drop-shadow-2xl" /></div>
        </div>
      </header>

      <section id="how-it-works" className="section-y container-page" aria-labelledby="how-title">
        <SectionHeading id="how-title" eyebrow="How it works" title="From what you've seen to what to do next" align="center" />
        <ol className="grid gap-6 md:grid-cols-3">
          {STEPS.map((s, i) => (
            <li key={s.title} className="card-soft card-lift p-7">
              <div className="mb-5 flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-primary-foreground"><s.icon className="h-6 w-6" aria-hidden="true" /></span><span className="font-display text-5xl font-extrabold text-primary/10">{i + 1}</span></div>
              <h3 className="text-xl font-bold">{s.title}</h3>
              <p className="mt-2 leading-relaxed text-muted-foreground">{s.body}</p>
            </li>
          ))}
        </ol>
      </section>

      <section className="bg-secondary/50 section-y" aria-labelledby="preview-title">
        <div className="container-page grid items-center gap-10 lg:grid-cols-[1fr_1.15fr]">
          <div>
            <SectionHeading id="preview-title" eyebrow="Example plan" title="What your plan looks like">Here's the start of a plan for someone who found droppings and gnaw marks in the kitchen, has children and a cat, and tried glue traps.</SectionHeading>
            <Button asChild variant="default" size="lg"><Link to="/quiz">Build mine<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></Button>
          </div>
          <div className="card-soft p-6 md:p-7" aria-label="Example plan preview">
            <p className="pill mb-4">Example only</p>
            <p className="font-display text-xl font-bold">{sample.status.label}</p>
            <ol className="mt-5 space-y-4">
              {sample.priorities.map((p, i) => (
                <li key={p.id} className="flex gap-3">
                  <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent-gradient text-sm font-extrabold text-accent-foreground">{i + 1}</span>
                  <div><p className="font-semibold leading-snug">{p.title}</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{firstSentence(p.detail, 170)}</p>{p.source && <div className="mt-2"><SourceBadge id={p.source} /></div>}</div>
                </li>
              ))}
            </ol>
            <p className="mt-5 border-t pt-4 text-sm text-muted-foreground">Plus {sample.actions.length - sample.priorities.length} more steps across today, this week and ongoing.</p>
          </div>
        </div>
      </section>

      <section className="section-y container-page" aria-labelledby="tools-title">
        <SectionHeading id="tools-title" eyebrow="Free tools" title="Useful on their own, even without the quiz" align="center">Each tool is short, practical and linked to its primary source.</SectionHeading>
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {TOOLS.map(t => (
            <Link key={t.to} to={t.to} className="card-soft card-lift group flex flex-col p-6">
              <span className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground"><ToolIcon name={t.icon} className="h-6 w-6" /></span>
              <h3 className="text-lg font-bold leading-snug">{t.title}</h3>
              <p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{t.blurb}</p>
              <span className="mt-4 inline-flex items-center gap-1.5 text-sm font-semibold text-primary">Open · {t.time}<ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" aria-hidden="true" /></span>
            </Link>
          ))}
        </div>
      </section>

      <section className="bg-secondary/50 section-y" aria-labelledby="compare-title">
        <div className="container-page">
          <SectionHeading id="compare-title" eyebrow="Free and Pro" title="Start free. Upgrade only if it helps" align="center">The free plan is complete on its own. Pro adds organisation for a month-long effort.</SectionHeading>
          <div className="card-soft overflow-hidden">
            <div className="overflow-x-auto" tabIndex={0} role="region" aria-label="Free and Pro comparison table, scrollable">
              <table className="w-full min-w-[34rem] text-left">
                <caption className="sr-only">Comparison of the free plan and the Pro Masterplan</caption>
                <thead>
                  <tr className="border-b bg-secondary/60">
                    <th scope="col" className="p-4 text-sm font-semibold">What's included</th>
                    <th scope="col" className="w-36 p-4 text-center text-sm font-semibold">Free</th>
                    <th scope="col" className="w-44 bg-[hsl(41_100%_60%/0.18)] p-4 text-center text-sm font-bold">Pro · {PRO_PRICE_LABEL}</th>
                  </tr>
                </thead>
                <tbody>
                  {COMPARE.map(([label, free, pro]) => (
                    <tr key={label} className="border-b last:border-0">
                      <th scope="row" className="p-4 text-sm font-medium">{label}</th>
                      <td className="p-4 text-center"><Cell v={free} /></td>
                      <td className="bg-[hsl(41_100%_60%/0.08)] p-4 text-center"><Cell v={pro} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
          <div className="mt-6 text-center"><Button asChild variant="premium" size="lg"><Link to="/pro">See what's inside Pro</Link></Button></div>
        </div>
      </section>

      <section className="section-y container-page" aria-labelledby="trust-title">
        <SectionHeading id="trust-title" eyebrow="Why you can trust it" title="Built on primary sources, with the limits stated">We don't use a black-box score. Every recommendation traces to a public source you can read yourself (pages reviewed {SOURCES_REVIEWED}).</SectionHeading>
        <div className="grid gap-5 md:grid-cols-2">
          {SOURCES.map(s => (
            <a key={s.id} href={s.url} target="_blank" rel="noopener noreferrer" className="card-soft card-lift flex items-start justify-between gap-4 p-5">
              <span><span className="block text-xs font-bold uppercase tracking-wider text-primary">{s.org}</span><span className="mt-1 block font-semibold">{s.label}</span></span>
              <ArrowRight className="mt-1 h-4 w-4 shrink-0 text-primary" aria-hidden="true" />
            </a>
          ))}
        </div>
        <div className="mt-8 grid gap-4 rounded-2xl border bg-card p-6 md:grid-cols-2">
          <div><h3 className="font-display text-lg font-bold">What it does</h3><ul className="mt-2 space-y-1.5 text-sm text-foreground/85"><li>Matches your answers to fixed, reviewable rules</li><li>Separates physical evidence from uncertain signs</li><li>Escalates real hazards to qualified help</li></ul></div>
          <div><h3 className="font-display text-lg font-bold">What it never does</h3><ul className="mt-2 space-y-1.5 text-sm text-foreground/85"><li>Diagnose an infestation or identify a species</li><li>Estimate how many mice are present</li><li>Show fake reviews, scores or promised results</li></ul></div>
        </div>
      </section>

      <section className="section-y container-page pt-0"><ProPromo compact /></section>

      <section className="bg-secondary/50 section-y" aria-labelledby="faq-title">
        <div className="container-read">
          <SectionHeading id="faq-title" eyebrow="Questions" title="Straight answers" align="center" />
          <Accordion type="single" collapsible className="space-y-3">
            {FAQ.map((f, i) => (
              <AccordionItem key={f.q} value={`q${i}`} className="card-soft border px-5">
                <AccordionTrigger className="py-5 text-left text-base font-semibold hover:no-underline">{f.q}</AccordionTrigger>
                <AccordionContent className="pb-5 text-base leading-relaxed text-muted-foreground">{f.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      <section className="bg-hero hero-pattern text-primary-foreground">
        <div className="container-read section-y text-center">
          <h2 className="text-3xl font-extrabold md:text-4xl">Ready for a plan you can start today?</h2>
          <p className="mx-auto mt-3 max-w-xl text-lg text-primary-foreground/85">It takes about two minutes and needs nothing from you but what you've seen.</p>
          <Button asChild variant="hero" size="xl" className="mt-7"><Link to="/quiz">Build my free plan<ArrowRight className="h-5 w-5" aria-hidden="true" /></Link></Button>
        </div>
      </section>
    </PageShell>
  );
}
