import { Link } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { PLANNER_LIMITATION, SOURCES } from "@/lib/report-generator";
const steps = [
  ["Record observations", "Separate physical signs from uncertain noises, odors and marks."],
  ["Organize safe next steps", "Plan accessible inspection, food storage, protected trapping and wet cleanup."],
  ["Monitor what changes", "Check actual evidence after cleanup and review the plan when activity continues."],
];
export default function Index() {
  return <div className="min-h-screen flex flex-col bg-background"><Navbar/>
    <header className="bg-hero text-primary-foreground"><div className="container mx-auto max-w-5xl px-4 py-16 md:py-24"><p className="text-sm font-semibold uppercase tracking-wider mb-5">MiceGoneGuide / Practical planning</p><h1 className="text-4xl md:text-6xl font-display font-bold leading-tight max-w-3xl mb-6">Personalized Mouse<br/>Control Planner</h1><p className="text-lg max-w-2xl mb-8">Organize inspection, trapping, cleanup and exclusion steps around the signs you report.</p><div className="flex flex-wrap gap-4"><Button variant="hero" size="lg" asChild><Link to="/quiz">Build my free plan</Link></Button><Button variant="hero-outline" size="lg" asChild><a href="#how-it-works">See how it works</a></Button></div><p className="text-sm max-w-2xl mt-8 leading-relaxed">{PLANNER_LIMITATION}</p></div></header>
    <main><section id="how-it-works" className="container mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-display font-bold mb-8">From observations to a useful checklist</h2><div className="grid md:grid-cols-3 gap-5">{steps.map(([title, text], i) => <article className="glass-card rounded-2xl p-6" key={title}><p className="text-sm text-primary font-semibold mb-3">Step {i + 1}</p><h3 className="text-xl font-semibold mb-3">{title}</h3><p className="text-muted-foreground">{text}</p></article>)}</div></section>
    <section className="bg-secondary/40"><div className="container mx-auto max-w-5xl px-4 py-12 grid md:grid-cols-2 gap-8"><div><h2 className="text-2xl font-display font-bold mb-4">What changes your plan?</h2><p className="mb-4">The observations you select determine inspection prompts. Room choices organize those prompts. Children and pets trigger trap-access precautions. Reported electrical or contamination hazards trigger qualified-help advice.</p><p className="text-sm text-muted-foreground">No population formula, species probability or disease score is calculated. Nothing in the plan confirms that a mouse is present or that a property is clear.</p></div><div className="glass-card rounded-2xl p-6"><h2 className="text-2xl font-display font-bold mb-4">Get the answer before an upsell</h2><p className="mb-4">View your observation summary, immediate steps, cleanup guidance, inspection checklist and printable PDF without entering an email.</p><p className="text-sm text-muted-foreground">Optional email check-ins and extended planning are separate. Product prices and paid-plan terms must be confirmed at checkout; purchasing a plan cannot guarantee a result.</p></div></div></section>
    <section className="container mx-auto max-w-5xl px-4 py-12"><h2 className="text-3xl font-display font-bold mb-6">Focused tools</h2><div className="grid sm:grid-cols-2 gap-5"><Link className="glass-card rounded-2xl p-6 block focus-visible:ring-2 focus-visible:ring-primary" to="/tools/calculator"><h3 className="text-xl font-semibold mb-3">Observation and action planner</h3><p className="text-muted-foreground">Turn a reported sign into a practical next step, without projecting mouse populations.</p></Link><Link className="glass-card rounded-2xl p-6 block focus-visible:ring-2 focus-visible:ring-primary" to="/tools/entry-points"><h3 className="text-xl font-semibold mb-3">Entry-gap inspection checklist</h3><p className="text-muted-foreground">Review accessible inspection areas and know when repairs need qualified help.</p></Link></div></section>
    <section className="container mx-auto max-w-5xl px-4 pb-14"><h2 className="text-2xl font-display font-bold mb-4">Sources and limits</h2><p className="mb-5 max-w-3xl">Guidance draws on public-health and university integrated pest-management resources. Linking to those resources does not mean their authors have reviewed or endorsed this planner.</p><ul className="space-y-3">{SOURCES.map(source => <li key={source.url}><a className="underline text-primary" href={source.url}>{source.label}</a></li>)}</ul><div className="mt-8"><Button variant="hero" size="lg" asChild><Link to="/quiz">Build my free plan</Link></Button></div></section></main><Footer/></div>;
}
