// Saves the free and Pro PDFs generated by the app, for visual review. Usage: node scripts/pdfs.mjs
import { chromium } from "@playwright/test";
import { mkdirSync } from "node:fs";

const base = process.env.BASE || "http://127.0.0.1:8787";
mkdirSync("evidence/pdfs", { recursive: true });
const answers = { evidence: ["droppings", "gnaw_marks", "damaged_wiring"], location: ["kitchen", "attic", "garage"], home_type: "townhouse", household: ["kids", "pets_cat"], previous: ["glue_traps", "ultrasonic"], food_storage: "mixed", duration: "weeks" };
const browser = await chromium.launch();
const ctx = await browser.newContext({ acceptDownloads: true, viewport: { width: 1280, height: 900 } });
await ctx.addInitScript(a => { try { localStorage.setItem("mgg.answers.v2", JSON.stringify(a)); } catch {} }, answers);
const page = await ctx.newPage();
await page.goto(base + "/plan", { waitUntil: "networkidle" });
let [d] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "Download free plan PDF" }).click()]);
await d.saveAs("evidence/pdfs/free.pdf");
await page.goto(base + "/payment-success?session_id=cs_test_PAID0000000001"); await page.waitForURL("**/pro");
[d] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "Download Pro PDF" }).click()]);
await d.saveAs("evidence/pdfs/pro.pdf");
await browser.close();
console.log("saved free.pdf and pro.pdf");
