import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const REPO='douphealth/mice-solver-pro', REF='ops/approved-publish-2026-10-02';
const RUN=process.env.GITHUB_RUN_ID, SOURCE='0721ca88c9111fd1648aa471667bb49cccd9f193';
const SITE='https://micegoneguide.com', APP='https://elimination.micegoneguide.com';
const ACCOUNT='5dc0401c38d9de0c6947fee40a210937', PROJECT='mice-solver-fixed';
const TMP=path.join(process.env.RUNNER_TEMP,'mgg-final-publication'), OUT='publication-evidence';
const TARGETS=[['posts',23,'how-to-get-rid-of-mice'],['posts',96,'signs-of-mice-infestation'],['posts',715,'how-to-get-rid-of-mice-in-walls'],['posts',3403,'best-mouse-traps-for-homes'],['posts',78,'humane-mouse-traps'],['pages',3525,'steel-wool-vs-copper-mesh-for-mice'],['posts',536,'rats-vs-mice-whats-the-difference'],['pages',3155,'mouse-removal'],['posts',22,'natural-mouse-repellents'],['posts',3533,'mouse-droppings']];
const ORIGINAL_HASHES=new Set(['0c59285924addd38af8607a51d9d8c99aef83a58ff1562242b6c3e74adf24b3b','22dcbf40bdd47378d07c4257c7f25323ce64cc15d5a5ae31e31443812dff0b39','53023d478283170f14da37211ea0ad5f6297db1fbd5dbe40cbc5d71c32732db6','81c5a1b16848fb7f19bc0a70036ff144351d9a616ac0033571875630e8c4d2c6','8cc5a4e4e0a9cf4756486f82fe1eabb2e211c2bab1491c9f9e9e041e514962ae']);
const check=(x,m)=>{if(!x)throw new Error(m)};
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const write=(f,d)=>fs.writeFileSync(f,typeof d==='string'?d:JSON.stringify(d,null,2),{mode:0o600});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const masked=[];
function mask(v){if(!v)return;masked.push(v);console.log('::add-mask::'+v.replaceAll('%','%25').replaceAll('\n','%0A').replaceAll('\r','%0D'));}
function safe(v){for(const s of masked)v=v.split(s).join('[REDACTED]');return v;}
async function request(url,headers={},method='GET',body){const r=await fetch(url,{method,headers:{'User-Agent':'MiceGoneGuide-Authorized-Publication/1.0',...headers},body:body===undefined?undefined:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(35000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{}return {status:r.status,headers:Object.fromEntries(r.headers),text,data};}
const gh=url=>request('https://api.github.com/repos/'+REPO+url,{'Authorization':'Bearer '+process.env.GH_READ_TOKEN});
function load(){const c=JSON.parse(fs.readFileSync(TMP+'/auth.json'));mask(c.wp.password);mask(c.cf_token);mask(Buffer.from(c.wp.username+':'+c.wp.password).toString('base64'));return c;}
function wpHeaders(c){return {'Authorization':'Basic '+Buffer.from(c.wp.username+':'+c.wp.password).toString('base64'),'Content-Type':'application/json'};}
async function wp(c,t,id){const r=await request(`${SITE}/wp-json/wp/v2/${t}/${id}?context=edit`,wpHeaders(c));check(r.status===200&&typeof r.data?.content?.raw==='string',`WP read ${t}/${id} HTTP ${r.status}`);return r.data;}
const cf=(c,p,method='GET',body)=>request(`https://api.cloudflare.com/client/v4/accounts/${ACCOUNT}/pages/projects/${PROJECT}`+p,{'Authorization':'Bearer '+c.cf_token,'Content-Type':'application/json'},method,body);
function decode(e){check(e.aad===RUN&&e.algorithm==='RSA-OAEP-SHA256+A256GCM','Invalid envelope');const key=crypto.privateDecrypt({key:fs.readFileSync(TMP+'/key.pem'),oaepHash:'sha256',padding:crypto.constants.RSA_PKCS1_OAEP_PADDING},Buffer.from(e.wrapped_key,'base64'));const b=Buffer.from(e.ciphertext,'base64'),d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(e.nonce,'base64'));d.setAAD(Buffer.from(RUN));d.setAuthTag(b.subarray(-16));const v=JSON.parse(Buffer.concat([d.update(b.subarray(0,-16)),d.final()]).toString());check(v.run_id===RUN&&v.expires>Date.now()/1000,'Expired command');return v;}
async function receive(phase){const end=Date.now()+42*60000;while(Date.now()<end){const r=await gh(`/contents/release/${phase}-${RUN}.json?ref=${encodeURIComponent(REF)}`);if(r.status===200){check(r.data.size<2000000,'Command too large');const c=decode(JSON.parse(Buffer.from(r.data.content,'base64').toString()));check(c.phase===phase,'Wrong phase');return c;}check(r.status===404,'Command read error');await sleep(8000);}throw new Error('Command timed out');}
async function init(){check(process.env.GITHUB_REPOSITORY===REPO,'Wrong repository');fs.mkdirSync(TMP,{recursive:true,mode:0o700});fs.mkdirSync(OUT,{recursive:true});const p=crypto.generateKeyPairSync('rsa',{modulusLength:3072,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});write(TMP+'/key.pem',p.privateKey);write(OUT+'/handshake.json',{run_id:RUN,source_commit:SOURCE,public_key:p.publicKey});}
async function inspect(){const c=await receive('auth');check(c.wp?.username==='micegoneguide'&&typeof c.cf_token==='string','Credential scope invalid');write(TMP+'/auth.json',c);load();const report={run_id:RUN,source_commit:SOURCE,posts:[],original_revisions:[],app:null};for(const [type,id,slug]of TARGETS){const p=await wp(c,type,id);check(p.slug===slug&&p.status==='publish','Unexpected WP record');report.posts.push({type,id,slug,status:p.status,url:p.link,title:p.title.raw,content:p.content.raw,content_sha256:sha(p.content.raw),modified_gmt:p.modified_gmt,featured_media:p.featured_media});if(TARGETS.slice(0,5).some(x=>x[1]===id)){const r=await request(`${SITE}/wp-json/wp/v2/${type}/${id}/revisions?per_page=20&context=edit`,wpHeaders(c));for(const rev of Array.isArray(r.data)?r.data:[]){const content=rev.content?.raw;if(typeof content==='string'&&ORIGINAL_HASHES.has(sha(content)))report.original_revisions.push({type,parent:id,revision_id:rev.id,content,content_sha256:sha(content)});}}}
const project=await cf(c,'');check(project.data?.success&&project.data.result.domains.includes('elimination.micegoneguide.com'),'Production Pages mapping mismatch');const p=project.data.result;report.app={account:ACCOUNT,project:PROJECT,domains:p.domains,branch:p.production_branch,previous_id:p.canonical_deployment?.id,previous_url:p.canonical_deployment?.url,previous_commit:p.canonical_deployment?.deployment_trigger?.metadata?.commit_hash,source_type:p.source?.type,source_repo:p.source?.config?.repo_name};const r=await request(APP+'/');check(r.status===200,'App not readable');write(OUT+'/before-index.html',r.text);report.assets=[];for(const m of r.text.matchAll(/<script[^>]+src=["']([^"']+)["']/g)){const u=new URL(m[1],APP);if(u.origin!==APP||!u.pathname.startsWith('/assets/'))continue;const asset=await request(u.href);check(asset.status===200,'Live bundle not readable');const file='before-'+path.basename(u.pathname);write(OUT+'/'+file,asset.text);report.assets.push({url:u.href,file,sha256:sha(asset.text),bytes:Buffer.byteLength(asset.text)});}
write(OUT+'/public-content-backup.json',report);write(TMP+'/before.json',report);console.log('Backed up '+report.posts.length+' published pages and '+report.original_revisions.length+' original pre-release revisions; exact Cloudflare project confirmed.');}
async function apply(){const c=load(),cmd=await receive('apply'),before=JSON.parse(fs.readFileSync(TMP+'/before.json'));const receipt={run_id:RUN,source_commit:SOURCE,wordpress:[],app:null,errors:[]};const save=()=>write(OUT+'/publication-receipt.json',receipt);
if(cmd.patches_sha){check(/^[a-f0-9]{40}$/.test(cmd.patches_sha),'Bad immutable patch SHA');const b=await gh('/git/blobs/'+cmd.patches_sha);check(b.status===200&&b.data.encoding==='base64','Patch unavailable');const patches=JSON.parse(Buffer.from(b.data.content,'base64').toString());check(Array.isArray(patches)&&patches.length<=10,'Bad patch list');const ready=[];for(const patch of patches){const original=before.posts.find(p=>p.id===patch.id&&p.type===patch.type);check(original&&original.content_sha256===patch.before_sha256,'Snapshot mismatch');let content=original.content;for(const edit of patch.edits){check(typeof edit.old==='string'&&edit.old.length>0&&typeof edit.new==='string','Bad exact edit');const parts=content.split(edit.old);check(parts.length===(edit.count||1)+1,'Replacement mismatch for '+original.slug);content=parts.join(edit.new);}check(sha(content)===patch.after_sha256&&content.length>1000,'Post-change checksum mismatch');const current=await wp(c,patch.type,patch.id);check(sha(current.content.raw)===patch.before_sha256,'Concurrent WP change: '+original.slug);ready.push({patch,original,content});}for(const {patch,original,content}of ready){const response=await request(`${SITE}/wp-json/wp/v2/${patch.type}/${patch.id}`,wpHeaders(c),'POST',{content});check(response.status===200,'WP write failed');const after=await wp(c,patch.type,patch.id);if(sha(after.content.raw)!==patch.after_sha256){write(OUT+'/normalization-'+patch.id+'.json',{expected:content,actual:after.content.raw});const restore=await request(`${SITE}/wp-json/wp/v2/${patch.type}/${patch.id}`,wpHeaders(c),'POST',{content:original.content});const restored=await wp(c,patch.type,patch.id);receipt.errors.push({id:patch.id,reason:'Unexpected WordPress normalization',restored:restore.status===200&&sha(restored.content.raw)===original.content_sha256});save();throw new Error('Stopped on WP normalization; original restore checked');}const publicPage=await request(original.url+'?mgg_release='+RUN);receipt.wordpress.push({id:patch.id,slug:original.slug,url:original.url,before_sha256:patch.before_sha256,after_sha256:sha(after.content.raw),raw_verified:true,public_http:publicPage.status,marker:publicPage.text.includes('data-mgg-release'),modified_gmt:after.modified_gmt});save();console.log('Published '+original.url);}}
if(cmd.app){check(cmd.app.source_commit===SOURCE&&cmd.app.previous_id===before.app.previous_id,'App source guard mismatch');check(cmd.app.live_asset_sha256===before.assets[0]?.sha256,'Live asset approval mismatch');const p=await cf(c,'');check(p.data?.result?.canonical_deployment?.id===before.app.previous_id,'Concurrent app deployment');check(fs.existsSync('app-source/dist/index.html'),'Build absent');const git=spawnSync('git',['rev-parse','HEAD'],{cwd:'app-source',encoding:'utf8'});check(git.stdout.trim()===SOURCE,'Wrong checked-out app');write('app-source/dist/mgg-release.json',{source_commit:SOURCE,run_id:RUN,published_at:new Date().toISOString()});const res=spawnSync('npx',['--offline','--yes','wrangler@4','pages','deploy','dist','--project-name',PROJECT,'--branch',before.app.branch||'main','--commit-hash',SOURCE,'--commit-message','Owner-approved evidence-led mouse control planner','--commit-dirty=true'],{cwd:'app-source',env:{...process.env,CLOUDFLARE_API_TOKEN:c.cf_token,CLOUDFLARE_ACCOUNT_ID:ACCOUNT,WRANGLER_SEND_METRICS:'false'},encoding:'utf8',timeout:240000,maxBuffer:2000000});console.log(safe((res.stdout||'')+'\n'+(res.stderr||'')));check(res.status===0,'Pages deploy failed');let ok=false,after;for(let i=0;i<20;i++){const marker=await request(APP+'/mgg-release.json?run='+RUN);after=await cf(c,'');if(marker.data?.run_id===RUN&&marker.data?.source_commit===SOURCE&&after.data?.result?.canonical_deployment?.latest_stage?.status==='success'){ok=true;break;}await sleep(5000);}receipt.app={verified:ok,url:APP,previous_id:before.app.previous_id,deployment_id:after.data?.result?.canonical_deployment?.id};if(!ok){const roll=await cf(c,`/deployments/${before.app.previous_id}/rollback`,'POST',{});receipt.app.rollback_http=roll.status;save();throw new Error('App verification failed; requested prior deployment rollback');}save();}
for(const original of before.posts){const p=await wp(c,original.type,original.id);const r=await request(original.url+'?mgg_verify='+RUN);write(OUT+'/after-'+original.slug+'.html',r.text);receipt.verified_pages ||= [];receipt.verified_pages.push({id:p.id,url:p.link,content_sha256:sha(p.content.raw),http:r.status,marker:r.text.includes('data-mgg-release'),canonical:(r.text.match(/<link[^>]*rel=["']canonical["'][^>]*>/i)||[])[0],modified_gmt:p.modified_gmt});}
for(const route of ['/','/quiz','/report','/tools/calculator','/robots.txt','/sitemap.xml']){const r=await request(APP+route+'?mgg_verify='+RUN);receipt.app_routes ||= [];receipt.app_routes.push({route,http:r.status,x_robots_tag:r.headers['x-robots-tag'],content_type:r.headers['content-type']});}save();console.log(JSON.stringify(receipt,null,2));}
try{const mode=process.argv[2];check(['init','inspect','apply'].includes(mode),'Unsupported mode');await ({init,inspect,apply})[mode]();}catch(e){console.error(safe(e.message));process.exitCode=1;}
